[package]
name = "messages"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
core_crate = { path = "../core", package = "core" }
serde.workspace = true
bytes.workspace = true
serde_json.workspace = true